spring:
  application:
    name: service-user

  mail: # JavaMailSender config
    maillink: http://localhost:8860/user-service-zuul/confirmed/
    host: smtp.qq.com
    port: 465
    username: 1220123963@qq.com
    password: gzbzxaemuhkuhbig
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    active: prod

---
spring:
  profiles: dev

  mail: # JavaMailSender config
    maillink: http://localhost:8860/user-service-zuul/confirmed/
    loginlink: http://localhost:4200

  datasource:
    url: jdbc:mysql://localhost:3306/fullstack?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

server:
  port: 8859

eureka:
  instance:
    prefer-ip-address: true   #开启显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #eureka页面显示IP地址：端口号
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: prod

  mail: # JavaMailSender config
    maillink: http://localhost:8860/user-service-zuul/confirmed/
    loginlink: http://localhost:4200

  datasource:
    url: jdbc:mysql://localhost:3306/fullstack?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

server:
  port: 8859

eureka:
  instance:
    prefer-ip-address: true   #开启显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #eureka页面显示IP地址：端口号
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/